import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Translator API Token */}
        <meta
          httpEquiv="origin-trial"
          content="AnPllZVk4twq3c6EyHIowL5bp3rqg+BtHD9274qV/HzaNDuLJ9pWa5dNZz5Tj9KCVwajB+atGkNGPR39pl2X1QIAAAB0eyJvcmlnaW4iOiJodHRwczovL2huZy0xMi1zdGFnZTAzLnZlcmNlbC5hcHA6NDQzIiwiZmVhdHVyZSI6IlRyYW5zbGF0aW9uQVBJIiwiZXhwaXJ5IjoxNzUzMTQyNDAwLCJpc1N1YmRvbWFpbiI6dHJ1ZX0="
        />
        {/* Language Detector API Token */}
        <meta
          httpEquiv="origin-trial"
          content="Ap3Pi97lzyAq4f2pQh5Dag6iOSRK+/KlM913NsnO8zicJOM26N+VIy6+XLFOx+CJidnf2qvWnSsA7XW6XP4pLw4AAAB6eyJvcmlnaW4iOiJodHRwczovL2huZy0xMi1zdGFnZTAzLnZlcmNlbC5hcHA6NDQzIiwiZmVhdHVyZSI6Ikxhbmd1YWdlRGV0ZWN0aW9uQVBJIiwiZXhwaXJ5IjoxNzQ5NTk5OTk5LCJpc1N1YmRvbWFpbiI6dHJ1ZX0="
        />
        {/* Summarizer API Token */}
        <meta
          httpEquiv="origin-trial"
          content="Arpmce/w+vb1yPJQGmhsyGlIBLuAtZk83V/lj6twsBfwQaP5xoEdW2z7sjbxlNl6RwdRuqSYFLcJIHz8D/GfAgYAAAB4eyJvcmlnaW4iOiJodHRwczovL2huZy0xMi1zdGFnZTAzLnZlcmNlbC5hcHA6NDQzIiwiZmVhdHVyZSI6IkFJU3VtbWFyaXphdGlvbkFQSSIsImV4cGlyeSI6MTc1MzE0MjQwMCwiaXNTdWJkb21haW4iOnRydWV9"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
